name: Release Binaries

on:
  push:
    tags:
      - 'v*'  # 태그가 'v'로 시작하는 경우에만 트리거 됩니다.

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ${{ matrix.target.runs-on }}
    strategy:
      matrix:
        target: 
          - runs-on: ubuntu-latest
            triplet: x86_64-unknown-linux-gnu
          - runs-on: ubuntu-latest
            triplet: aarch64-unknown-linux-gnu
          - runs-on: macos-latest
            triplet: aarch64-apple-darwin

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target.triplet }}
        override: true

    - name: Install Cross for cross-compilation
      run: cargo install cross

    - name: Build for ${{ matrix.target.triplet }}
      run: cross build --release --target ${{ matrix.target.triplet }}

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target.triplet }}-binary
        path: target/${{ matrix.target.triplet }}/release/kubectl-check

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        pattern: '*-binary'

    - run: |
        ls -alR

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/x86_64-unknown-linux-gnu/release/kubectl-check
          target/aarch64-unknown-linux-gnu/release/kubectl-check
          target/aarch64-apple-darwin/release/kubectl-check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
